### PR TITLE
Update trilead-ssh2 to build217-jenkins-10

### PR DESCRIPTION
**Pull request by paladox**

### CODE REVIEW

**Comment by paladox** [comment]
@mc1arke please review / merge?

**Comment by mc1arke** [comment]
I'm not going to merge this just now. We need to keep this at the same version as in Jenkins core - the dependency is set at 'provided' so dependent items actually get the copy of Trilead provided by the underlying app/container. We can only safely change this when all plugins that use Trilead are depending on this plugin and we start masking the Trilead classes in Core.

I don't expect there to be any change to this plugin until the point we turn on masking and bump the Trilead version to make this plugin the master of Trilead.

**Comment by paladox** [comment]
@mc1arke but won't this plugin need to use the newer version of trilrad when updating plugin does to depend on this new plugin? Might as well update trilead in Jenkins core now for the next release and backport it to the latest lts release as the lts release supports java 7 but newer releases now support java 8.

**Comment by mc1arke** [comment]
@paladox with the plugin as it currently is, it's purely acting as an 'shim' between Jenkins and the dependent plugins, so the version in the plugin should reflect the version in Jenkins core. Only once Jenkins core has bumped the version should we update the version in this plugin.

**Comment by reedloden** [comment]
Jenkins has been updated in https://github.com/jenkinsci/jenkins/commit/b17d0763709be35d39f16d6af7afaf765ac6cf92, so can this be merged now?

**Comment by mc1arke** [comment]
Whilst Jenkins core continues to be the provider of Trilead, this plugin *must* keep the same version of Trilead as the version provided in the version of Jenkins core that this plugin depends on. If we don't do this then any plugins that depend on this will get exceptions related to missing classes and methods when they try and execute methods from newer Trilead versions that don't exist in the version of Jenkins they're currently running in.

Once this plugin becomes the provider of Trilead and masks any Trilead classes in core then we can freely update the version at will.

**Pull request closed without merging**
