### PR TITLE
Use gson-api plugin

### PR DESCRIPTION
**Pull request by jonesbusy**
Use gjson-api plugin

- [x] Remove version when bom released https://github.com/jenkinsci/bom/pull/2723

### Submitter checklist

- [ ] JIRA issue is well described
- [x] Appropriate autotests or explanation to why this change has no tests

### CODE REVIEW

**Review by kuisathaverat — APPROVED** [review]

**Comment by basil** [comment]
@kuisathaverat Shall we do a new release for 2023? :smile:

**Comment by kuisathaverat** [comment]
>@kuisathaverat Shall we do a new release for 2023?

IIRC there are no changes in the trilead-ssh2 dependency, so the only changes since the last release, so it only has changes on Jenkins plugins dependencies. We can release it next week, the change will not affect users.

https://github.com/jenkinsci/trilead-api-plugin/releases/tag/untagged-fb7cb791135a3b28966c

**Comment by kuisathaverat** [comment]
done https://github.com/jenkinsci/trilead-api-plugin/releases/tag/2.133.vfb_8a_7b_9c5dd1

**Comment by kuisathaverat** [comment]
This change causes conflits with other plugins that not use the gson-api plugin https://issues.jenkins.io/browse/JENKINS-72441

**Comment by kuisathaverat** [comment]
https://github.com/jenkinsci/gson-api-plugin/issues/7

**Comment by basil** [comment]
Fixed in https://github.com/jenkinsci/artifact-manager-s3-plugin/pull/447.

**Pull request merged**
