### PR TITLE
Modernize to Jenkins 2.440.3

### PR DESCRIPTION
**Pull request by sghill-rewrite**
Hi!

This PR aims to move this plugin to the [recommended](https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/) Jenkins baseline version.

If there are additional requirements for accepting PRs - such as additional lag time before adopting a baseline - feel free to reply in the comments.

## Testing done
Ran `mvn clean verify`.

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

Refs: sghill-rewrite/campaigns#4

Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.jenkins.ModernizePlugin?organizationId=SmVua2lucyBDSQ%3D%3D

### CODE REVIEW

**Comment by kuisathaverat** [comment]
I keep compatibility with the latest two LTS or 6 months, so it is not time to bump to 2.440 yet

**Comment by sghill** [comment]
Thanks for the context!

I see the plugin is currently on 2.426.3. Does this mean you'd move to 2.440.3 on the release of 2.462.1, 2.462.3, or the next chosen LTS?

**Comment by kuisathaverat** [comment]
I usually make the bump on August, I check for the version released on February or so, in this case 2.440.1 (2024-02-21)

**Comment by sghill** [comment]
Thanks! I captured this preference so I won't ping you with new Jenkins baseline too early again.

**Pull request closed without merging**
